apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  selector:
    matchLabels:
       app: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      name: mysqldb
      labels: 
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "#Amma1991"
              
            - name: MYSQL_DATABASE
              value: angulardb
          ports:
            - containerPort: 3306
              name: mysqldb 
               
---


apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  selector:
    app: mysqldb
  clusterIP: None
  ports:
    - targetPort: 3306
      port: 3306
